# Generated by Django 3.2.15 on 2022-08-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('core', '0003_auto_20220821_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(upload_to='property_images'),
        ),
    ]
