# Generated by Django 3.2.15 on 2022-08-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
