# Generated by Django 3.2.15 on 2022-09-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220924_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
