# Generated by Django 3.2.15 on 2022-09-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_property_bathroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='garages'),
        ),
        migrations.AlterField(
            model_name='property',
            name='room',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rooms'),
        ),
    ]
