# Generated by Django 3.2.15 on 2022-09-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220927_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='about',
        ),
    ]
